"""
This modules leverages the AI Feynman library to perform symbolic regression on a given dataset.
It allows for dataset sampling, feature selection, and saves intermediate results to a specified file.

Usage:
    python aifeynman_model.py --dataset <path_to_dataset> --dataset_size <size> --features <feature_list> --temp_file <path_to_temp_file>
"""

import numpy as np
import argparse
import pandas as pd
from aifeynman import S_run_aifeynman
import os
import shutil

# Hyperparameters for AI Feynman
OPERATORS = '+*-D~ILEA'  # Operators used in the symbolic regression
BF_TRY_TIME = 30  # Maximum time (in seconds) allowed for the brute-force search step
POLYFIT_DEGREE = 4  # Degree of the polynomial used in the polynomial fitting stage
NN_EPOCHS = 40  # Number of training epochs for the neural network regression stage
DATA_PATHDIR = './data/datasets/'  # Path to the directory containing the text format dataset
TEST_PERCENTAGE = 20  # Percentage of data to use for testing
FILENAME = 'mystery.txt'  # Name of the dataset file

def load_dataset(file_path, dataset_size=None, features=None):
    """
    Load dataset from a CSV file, sample it if a dataset size is specified, and select specific features if provided.

    Args:
        file_path (str): Path to the CSV file containing the dataset.
        dataset_size (int, optional): Number of samples to use from the dataset. Defaults to None.
        features (str, optional): Comma-separated list of features to use from the dataset. Defaults to None.

    Returns:
        pd.DataFrame: The loaded and optionally sampled dataset.
    """
    data = pd.read_csv(file_path)

    if features and features != "all":
        feature_list = features.split(',')
        data = data[feature_list]

    if dataset_size:
        dataset_size = min(dataset_size, len(data))
        data = data.sample(n=dataset_size)

    return data

def find_best_formula(data, temp_file, features):
    """
    Run AI Feynman to find the best formula, saving progress to a specified temporary file.

    Args:
        data (pd.DataFrame): The dataset to use for symbolic regression.
        temp_file (str): Path to the temporary file to save intermediate results.
        features (str): Comma-separated list of features to use from the dataset.
    """
    X = data.iloc[:, :-1].values
    y = data.iloc[:, -1].values

    data_array = np.concatenate((X, y[:, np.newaxis]), axis=1)
    np.savetxt(DATA_PATHDIR + 'mystery.txt', data_array)
    np.savetxt(DATA_PATHDIR + '7ops.txt', np.array([OPERATORS]), fmt='%s')

    open('./data/temp_results/temp_formula_aifeynman_dynamic.txt', 'w').close()
    open('./data/temp_results/temp_formula_aifeynman_static.txt', 'w').close()

    feature_list = features.split(',')

    try:
        S_run_aifeynman.run_aifeynman(
            pathdir=DATA_PATHDIR,
            filename=FILENAME,
            BF_try_time=BF_TRY_TIME,
            BF_ops_file_type='7ops.txt',
            polyfit_deg=POLYFIT_DEGREE,
            NN_epochs=int(NN_EPOCHS),
            vars_name=feature_list,
            test_percentage=TEST_PERCENTAGE,
        )
        
        copy_solution_to_temp('results/solution_' + FILENAME, temp_file)

    except TimeoutError:
        print("AI Feynman process timed out.")

def copy_solution_to_temp(solution_file, temp_file):
    """
    Copy the solution file to the specified temporary file.

    Args:
        solution_file (str): Path to the solution file generated by AI Feynman.
        temp_file (str): Path to the temporary file to save the solution.
    """
    try:
        shutil.copy(solution_file, temp_file)
        print(f"Solution file copied to {temp_file}")
    except FileNotFoundError:
        print("Solution file not found. Ensure AI Feynman completed successfully.")
    except Exception as e:
        print(f"An error occurred while copying the file: {e}")

def main():
    """
    Main function to parse arguments and run the AI Feynman process.
    """
    parser = argparse.ArgumentParser(description='Find the best formula using AI Feynman')
    parser.add_argument('--dataset', required=True, help='Path to the dataset CSV file')
    parser.add_argument('--dataset_size', type=int, help='Number of samples to use from the dataset')
    parser.add_argument('--features', type=str, help='Comma-separated list of features to use from the dataset')
    parser.add_argument('--temp_file', required=True, help='Path to the temporary file to save intermediate results')

    args = parser.parse_args()
    data = load_dataset(args.dataset, args.dataset_size, args.features)
    find_best_formula(data, args.temp_file, args.features)

if __name__ == '__main__':
    main()