# config.yaml
data_type: "dynamic"  # Options: "dynamic" or "static"

# Model selection
models: [] #["pysr", "pysindy", "kan", "dso"] #, "aifeynman", "dso", "kan", "pysr"]

output_extension: {
    "pysindy": "txt",
    "aifeynman": "txt",
    "dso": "txt",
    "kan": "txt",
    "pysr": "csv",  # pysr specifically uses csv
}

# Feature lists for static and dynamic datasets
features:
  static: "k_off,k_D,k_cat,tK,P_u,kcat_cg"  # Comma-separated list of features for static data
  dynamic: "k_off,k_D,k_cat,tK,P_u,k_inact,kcat_cg"  # Comma-separated list of features for dynamic data

# Target feature for the dataset
target_feature: "kcat_cg"  # Target feature to be placed as the last column of the dataset

# Timeout duration in seconds (e.g., 2 min * 60 = 120 seconds)
timeout_duration: 600

discovery_scales: '{"pysindy": "linear", "aifeynman": "log", "dso": "log", "kan": "log", "pysr": "linear"}'

# Dataset sizes for each method
dataset_sizes:
  pysindy: 10000       # PySINDy needs around 100-1000 samples
  aifeynman: 5000     # AI Feynman needs around 500-5000 samples
  dso: 10000          # DSO needs around 2000-10000 samples
  kan: 10000          # KAN needs around 2000-10000 samples
  pysr: 10000         # PySR needs around 1000-10000 samples
  nn: 10000           # Neural network needs around 1000-10000 samples

data_proportion: 0.0001  # Proportion of data to be used for integrator and plot method