"""Select the frozen PySR configuration from the grid sweep, and emit Table S10.

This is the selection step described in the v5 SI Methods ("PySR configuration
selection"). It was originally done by hand, which meant the manuscript's central
defence -- that the configuration was picked on *training* performance only, so the
held-out top-GFP bins played no part in it -- rested on an unscripted calculation.
This module makes the rule executable and its output diffable.

The rule, in full:

  * Restrict the sweep to the arms that keep division and use no unary operators.
    Division is required to express saturating, Michaelis-Menten-like rate laws; the
    unary-operator and no-division arms explore a different hypothesis and are not
    candidates. This leaves 72 of the 288 arms actually run.
  * Score each arm by the MEDIAN integrated-trajectory R2 ON THE TRAINING GFP BINS,
    pooled over its six development contexts x three seeds (18 fits per arm).
  * Take the highest. Ties break on the arm name so the result is deterministic.

Held-out (`ode_r2`) columns are read only to be *reported* alongside the ranking, never
to rank. The assertion at the end of `select()` enforces that.

Usage:
    python select_pysr_config.py \
        --screen data/experimental/runs/pysr_config_sweep/metrics/screen_final.csv \
        --output-table  .../metrics/table_s10_config_sweep.csv \
        --output-config .../selected_config.tsv
"""
from __future__ import annotations

import argparse
import re
import sys

import pandas as pd

# Arm names are generated by sweeps/make_grid_arms.py; parsing them back out is how the
# per-hyperparameter columns of Table S10 are recovered.
ARM_RE = re.compile(
    r"^it(?P<max_iterations>\d+)_p(?P<populations>\d+)_ps(?P<population_size>\d+)_"
    r"ms(?P<max_size>\d+)_par(?P<parsimony>\d+)_u(?P<unary>\w+)_b(?P<binary>\w+)$"
)

# The candidate family: division retained, no unary operators.
CANDIDATE_UNARY = "none"
CANDIDATE_BINARY = "div"

RANK_COLUMN = "median_train_r2"


def parse_arms(screen: pd.DataFrame) -> pd.DataFrame:
    fields = screen["arm"].astype(str).str.extract(ARM_RE)
    bad = fields["max_iterations"].isna()
    if bad.all():
        raise SystemExit(
            f"no grid-style arm names in the screen CSV (first few: "
            f"{sorted(screen['arm'].astype(str).unique())[:3]}) -- wrong input file?"
        )
    if bad.any():
        dropped = sorted(screen.loc[bad, "arm"].astype(str).unique())
        print(f"note: dropping {int(bad.sum())} fits with non-grid arm names: {dropped}")
    out = pd.concat([screen, fields], axis=1)[~bad].copy()
    for col in ("max_iterations", "populations", "population_size", "max_size"):
        out[col] = out[col].astype(int)
    # "par01" -> 0.1, "par08" -> 0.8, "par30" -> 3.0
    out["parsimony"] = out["parsimony"].map(
        lambda s: float(f"{s[0]}.{s[1:]}") if len(s) > 1 else float(s)
    )
    return out


def select(screen: pd.DataFrame) -> tuple[pd.DataFrame, pd.Series]:
    """Rank the candidate arms on training R2. Returns (table, winning row)."""
    fits = parse_arms(screen)
    if "ode_r2_train" not in fits.columns:
        raise SystemExit(
            "screen CSV has no 'ode_r2_train' column; the configuration must be chosen "
            "on training performance, so this file cannot be used for selection."
        )

    candidates = fits[
        (fits.unary == CANDIDATE_UNARY) & (fits.binary == CANDIDATE_BINARY)
    ].copy()
    if candidates.empty:
        raise SystemExit(
            f"no arms with unary={CANDIDATE_UNARY}, binary={CANDIDATE_BINARY}"
        )

    hyperparams = ["max_iterations", "populations", "population_size", "max_size",
                   "parsimony"]
    table = (
        candidates.groupby(["arm"] + hyperparams, as_index=False)
        .agg(
            n_fits=("ode_r2_train", "size"),
            median_train_r2=("ode_r2_train", "median"),
            # Reported for transparency only -- never used to rank.
            median_heldout_r2=("ode_r2", "median"),
            max_heldout_r2=("ode_r2", "max"),
            n_heldout_ge_06=("ode_r2", lambda s: int((s >= 0.6).sum())),
        )
    )
    # Deterministic order: primary key is training R2, tie-break on the arm name so a
    # re-run cannot silently pick a different arm out of a tied group.
    table = table.sort_values([RANK_COLUMN, "arm"], ascending=[False, True])
    table.insert(0, "train_rank", range(1, len(table) + 1))
    table = table.reset_index(drop=True)

    winner = table.iloc[0]

    # Guard the manuscript's claim: the winner must be the training-R2 argmax, and must
    # not also happen to be the held-out argmax by construction of the rule.
    assert winner[RANK_COLUMN] == table[RANK_COLUMN].max(), "ranking is not on train R2"
    return table, winner


def config_flags(winner: pd.Series) -> str:
    return (
        f"--max-iterations {int(winner.max_iterations)} "
        f"--populations {int(winner.populations)} "
        f"--population-size {int(winner.population_size)} "
        f"--max-size {int(winner.max_size)} "
        f"--parsimony {winner.parsimony:g}"
    )


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--screen", required=True,
                    help="Sweep screen CSV (one row per arm x marker x seed).")
    ap.add_argument("--output-table", required=True,
                    help="Table S10 destination: all candidate arms, train-ranked.")
    ap.add_argument("--output-config", required=True,
                    help="TSV destination: the selected arm, in run_markers.py flag form.")
    ap.add_argument("--test-size", default="0.2",
                    help="OOD split fraction recorded alongside the selected arm.")
    ap.add_argument("--expect-arms", type=int, default=72,
                    help="Fail if the candidate family is not this size (0 to disable). "
                         "The manuscript states 72; a change here is a change to Table S10.")
    args = ap.parse_args(argv)

    screen = pd.read_csv(args.screen)
    table, winner = select(screen)

    if args.expect_arms and len(table) != args.expect_arms:
        raise SystemExit(
            f"candidate family has {len(table)} arms, expected {args.expect_arms}. "
            f"The manuscript reports a {args.expect_arms}-configuration sweep -- either "
            f"the sweep inputs changed or the wrong screen CSV was passed."
        )

    table.round(6).to_csv(args.output_table, index=False)

    flags = config_flags(winner)
    with open(args.output_config, "w") as fh:
        fh.write("arm\ttest_size\textra_flags\n")
        fh.write(f"{winner.arm}\t{args.test_size}\t{flags}\n")

    n_markers = screen["marker"].nunique()
    print(f"=== PySR configuration selection ===")
    print(f"  candidates    : {len(table)} arms "
          f"(unary={CANDIDATE_UNARY}, binary={CANDIDATE_BINARY})")
    print(f"  development   : {n_markers} contexts, {int(winner.n_fits)} fits per arm")
    print(f"  ranked on     : median integrated R2 on the TRAINING GFP bins")
    print(f"\n  SELECTED      : {winner.arm}")
    print(f"  train rank    : {int(winner.train_rank)}/{len(table)} "
          f"(median train R2 {winner.median_train_r2:.3f})")
    print(f"  flags         : {flags}")
    print(f"\n  held-out numbers for the selected arm, for reference only:")
    print(f"    median {winner.median_heldout_r2:.3f}, max {winner.max_heldout_r2:.3f}, "
          f"{int(winner.n_heldout_ge_06)}/{int(winner.n_fits)} fits >= 0.6")

    heldout_best = table.loc[table.median_heldout_r2.idxmax()]
    if heldout_best.arm != winner.arm:
        print(f"\n  (the held-out-best arm is a different one, {heldout_best.arm} at "
              f"median {heldout_best.median_heldout_r2:.3f} — as expected, since "
              f"selection never reads held-out data)")

    print(f"\n  Table S10 -> {args.output_table}")
    print(f"  config    -> {args.output_config}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
