PYSR_CONFIG = {
    'niterations': 300,
    'population_size': 30,
    'populations': 15,
    'binary_operators': ["+", "*", "/", "-"],
    'unary_operators': ["exp", "log"],
    'maxsize': 30,
    'parsimony': 1,
    'verbosity': 0,
    'batching': True,
    'annealing': True,
    'elementwise_loss': "my_loss(x,y)=(log(max(x,0)+1e-25)-log(max(y,0)+1e-25))^2",
    'parallelism': 'serial',
    'deterministic': True,
}